### ISSUE TITLE
where is xbgmsharp/postgsail-vuestic

### ISSUE THREAD

**Issue by fbretmounet** [xbgmsharp/postgsail#1]
@xbgmsharp, I appreciate the contributions.
When trying to run docker-compose, it complains that it can't find the xbgmsharp/postgsail-vuestic image.
I checked the standard repos but can't find any reference to that image. where can I pull it from?

Thanks
-Fred

**Comment by xbgmsharp** [comment]
For some reason the build images is not working xbgmsharp/postgsail-vuestic.
https://github.com/xbgmsharp/vuestic-postgsail/actions/workflows/docker.yml
I could not figure it out, yet i can't reproduce the issue locally.

**Comment by fbretmounet** [comment]
When trying to build vuestic I get the following error:
src/components/va-charts/VaChart.vue:2:64 - error TS2322: Type '{ datasets: _DeepPartialObject<{ line: LineControllerDatasetOptions & FillerControllerDatasetOptions; bar: BarControllerDatasetOptions; ... 5 more ...; radar: RadarControllerDatasetOptions & FillerControllerDatasetOptions; }> | { ...; }; ... 31 more ...; scales?: _DeepPartialObject<...> | undefined; }' is not assignable to type '_DeepPartialObject<CoreChartOptions<"pie"> & ElementChartOptions<"pie"> & PluginChartOptions<"pie"> & DatasetChartOptions<"pie"> & ScaleChartOptions<...> & DoughnutControllerChartOptions> | ... 4 more ... | undefined'.
  Type '{ datasets: _DeepPartialObject<{ line: LineControllerDatasetOptions & FillerControllerDatasetOptions; bar: BarControllerDatasetOptions; ... 5 more ...; radar: RadarControllerDatasetOptions & FillerControllerDatasetOptions; }> | { ...; }; ... 31 more ...; scales?: _DeepPartialObject<...> | undefined; }' is not assignable to type '_DeepPartialObject<CoreChartOptions<"bar"> & ElementChartOptions<"bar"> & PluginChartOptions<"bar"> & DatasetChartOptions<"bar"> & ScaleChartOptions<...> & BarControllerChartOptions>'.
    Types of property 'animation' are incompatible.
      Type 'boolean | _DeepPartialObject<AnimationSpec<"line" | "bar" | "bubble" | "pie" | "doughnut"> & { onProgress?: ((this: Chart<keyof ChartTypeRegistry, (number | ... 2 more ... | null)[], unknown>, event: AnimationEvent) => void) | undefined; onComplete?: ((this: Chart<...>, event: AnimationEvent) => void) | undefined; }>' is not assignable to type 'false | _DeepPartialObject<AnimationSpec<"bar"> & { onProgress?: ((this: Chart<keyof ChartTypeRegistry, (number | ScatterDataPoint | BubbleDataPoint | null)[], unknown>, event: AnimationEvent) => void) | undefined; onComplete?: ((this: Chart<...>, event: AnimationEvent) => void) | undefined; }> | undefined'.
        Type 'true' is not assignable to type 'false | _DeepPartialObject<AnimationSpec<"bar"> & { onProgress?: ((this: Chart<keyof ChartTypeRegistry, (number | ScatterDataPoint | BubbleDataPoint | null)[], unknown>, event: AnimationEvent) => void) | undefined; onComplete?: ((this: Chart<...>, event: AnimationEvent) => void) | undefined; }> | undefined'.

2   <component :is="chartComponent" ref="chart" class="va-chart" :chart-options="chartOptions" :chart-data="data" />
                                                                 ~~~~~~~~~~~~~~



Found 1 error in src/components/va-charts/VaChart.vue:2

Seems your build is experiencing the same issue.

Not having any Vue experience, it seems the documentation suggests you may have missed adding a few files to git in the 
 /src/components/va-charts folder?

You could try cloning the vuestic-postgsail repo in a different folder and running a build from there?
