### ISSUE TITLE
telegram-bot container runs and gets in a limited reboot loop even with PGSAIL_TELEGRAM_BOT_TOKEN commented out

### ISSUE THREAD

**Issue by DBKenshin** [xbgmsharp/postgsail#4]
I'm trying to get everything set up and running, but as the title says, the telegram-bot container is running and just repeatedly failing and restarting itself

> 2023-11-22 18:04:13     raise exceptions.ValidationError('Token is invalid!')
> 2023-11-22 18:04:13 aiogram.utils.exceptions.ValidationError: Token is invalid!\

and such. But I've got the token line commented out (as it is left by default).

**Comment by xbgmsharp** [comment]
You need to have your own Telegram bot API token, by default it is empty as Telegram is not mandatory.
