### ISSUE TITLE
Imperial Units

### ISSUE THREAD

**Issue by SCarns** [xbgmsharp/postgsail#5]
Turning on "Imperial Units" doesn't seem to convert anything to imperial units. Turning it on, everything is still displayed in ºC.

**Comment by xbgmsharp** [comment]
True, it is not implemented yet, will do.

**Comment by xbgmsharp** [comment]
Done via https://github.com/xbgmsharp/vuestic-postgsail/commit/20224e47dde7bd8c24b187dd62d5b36a36c41fef and https://github.com/xbgmsharp/vuestic-postgsail/commit/d7eef2317ad08d88773581b989f1098b5bf38656
