### ISSUE TITLE
Authentication error in provisioning with Grafana

### ISSUE THREAD

**Issue by lokasoft** [xbgmsharp/postgsail#8]
I have installed pgsail using the docker-compose file on Ubuntu 20.04, overall it works but the grafana provisioning does not seem to work.
In the job_run_details I see the following errors:

_ERROR:  plpy.Error: ('Error grafana add vessel org %', {'extra': None, 'message': 'Unauthorized', 'messageId': 'auth.unauthorized', 'statusCode': 401, 'traceID': ''})
CONTEXT:  Traceback (most recent call last):
  PL/Python function "grafana_py_fn", line 41, in <module>
    plpy.error('Error grafana add vessel org %', r.json())
PL/Python function "grafana_py_fn"
SQL statement "SELECT grafana_py_fn(data_rec.name, data_rec.vessel_id, data_rec.owner_email, app_settings)"
PL/pgSQL function cron_process_grafana_fn() line 25 at PERFORM_

Looking the the "gafana_py_fn" I don't see how the authentication with the grafana api is done, do I need to add a specific user in grafana ?

The servers are running behing haproxy, I have configured the public external urls in the app_settings.app_grafana_admin_uri and app.url.

In the .env file I have configured al the passwords as in the documentation.

Is there something I am missing?

Lex

**Comment by xbgmsharp** [comment]
Hello,
Thanks for using PostgSail. Very good point, there is no provisioning grafana as it is single user. You can directly connect to grafana as admin to create your own dashboard.
