### ISSUE TITLE
Cannot sign up new user

### ISSUE THREAD

**Issue by jsextl** [xbgmsharp/postgsail#9]
Hallo!

First of all thank you very much for this interesting project - I started to setup local installation using docker and Apache Reverse Proxy with official site and SSL certificates - works all well.

However I cannot sign up a new user - on the server side I see the following errors in the API container:

WARNING:  Register new account email:[jonny@bndlg.de]
16/Jul/2024:13:19:07 +0000: {"code":"PT551","details":"Invalid vessel","hint":"Unknown vessel","message":"Vessel Required"}

I have no clue why this happens and how to debug / solve the problem.

Thanks a lot for any input!

Best regards,
Jonas

**Comment by xbgmsharp** [comment]
Base on the error message, the user is already register, however you now need to register a vessel for this user.

**Comment by jsextl** [comment]
Well yes I registered a user - however no email got sent out and the user is stuck in the verification process. The logged error appear right after clicking to register the user.

How can I register a vessel?

is there a way to work around the verification process?

**Comment by xbgmsharp** [comment]
You might want to read the advanced configuration.
https://github.com/xbgmsharp/postgsail/blob/main/docs/ERD/README.md

**Comment by jsextl** [comment]
I read this:

You can skip the otp, add or update json key value to the account preference.

"email_valid": true

But where do I set this setting? In the docker-compose file? Or where else?

**Comment by xbgmsharp** [comment]
Feel free to contribute by improving the documentation.
It is all about SQL. The users preferences are store in the `accounts` table on the `preferences` column. You need an SQL prompt or SQL editor like pgadmin or DBeaver.
```sql
SELECT * FROM auth.accounts;
```

**Comment by jwrozelle** [comment]
First, I'm so excited to get this working

I've been running into a similar issue. The "sign up" button is simply unresponsive. I reviewed the discord conversation on this, tried installing several different ways on several different servers, and still can't get it to work...

**Comment by xbgmsharp** [comment]
Ping me on discord to solve the issue.
